version: '3'
services:
  db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes: 
      - ./migrations/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
  api:
    image: omniward:1.0.0
    ports:
      - 8081:8081
    depends_on:
    - db
    links: 
    - db:omniward.db