name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
         image: postgres
         env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
         ports: 
           - 5432:5432
         volumes: 
           - ~/migrations/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clojure cli
        uses: DeLaGuardo/setup-clojure@11.0
        with: 
         cli: 1.10.1.693
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
         path: |
            ~/.m2
         key: cljdeps-${{ hashFiles('deps.edn') }}
         restore-keys: cljdeps-
      - name: Execute clojure code
        run: clojure -M:test
