name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: start postgres with docker
        uses: addnab/docker-run-action@v3
        with:
          image: postgres
          options: |
            -v ${{ github.workspace }}/migrations/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
            -p 5432:5432
      - name: Install clojure cli
        uses: DeLaGuardo/setup-clojure@11.0
        with: 
         cli: 1.10.1.693
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
         path: |
            ~/.m2
         key: cljdeps-${{ hashFiles('deps.edn') }}
         restore-keys: cljdeps-
      - name: Execute Tests
        run: clojure -M:test
